# Domain adaptation training
# Replaces run_domain_adapt.sh

slurm_profile: grete_shared_80gb

env:
  type: conda
  name: synapse

script: "training/train_mito_domain_adaptation.py"
args:
  experiment_name: "domain-adapt-cryoet-ps32512-bs1"
  data_dir: "/scratch-grete/projects/nim00007/cryo-et-luca/"
  checkpoint_path: "/scratch-grete/usr/nimlufre/synapse/mito_segmentation/checkpoints/mitotomo-net32-bs2-ps32512-lr1e-4-downscaled"
  confidence_threshold: 0.5
  n_iterations: 30000
  batch_size: 1
  patch_shape: [32, 512, 512]
