# Domain adaptation for cryo-ET data
# Replaces run_domain_adapt_cryo.sh

slurm_profile: grete_shared_80gb

env:
  type: micromamba
  path: /mnt/lustre-grete/usr/u12103/envs/synapse

script: "training/domain_adapt_mito_cryoet.py"
args:
  experiment_name: "domain-adapt-cryoet-ps32512-bs1"
  data_dir: "/mnt/lustre-emmy-hdd/projects/nim00007/data/synaptic-reconstruction/wichmann/extracted/endbulb_of_held/"
  checkpoint_path: "/scratch-grete/usr/nimlufre/synapse/mito_segmentation/checkpoints/mitotomo-net32-bs2-ps32512-lr1e-4-downscaled"
  confidence_threshold: 0.5
  n_iterations: 30000
  batch_size: 1
  patch_shape: [32, 512, 512]
